steps:
  # --- Build & Deploy Backend ke Cloud Run ---
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-notes-vey", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-notes-vey"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "backend",
        "--image",
        "gcr.io/$PROJECT_ID/backend-notes-vey",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

  # --- Deploy Frontend ke App Engine ---
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && cd frontend_bc && gcloud app deploy --quiet --no-promote",
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
