steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking for frontend changes..."
        git fetch origin main
        CHANGED_FILES=$(git diff --name-only $COMMIT_SHA^ $COMMIT_SHA)
        echo "Changed files:"
        echo "$CHANGED_FILES"
        echo "$CHANGED_FILES" | grep '^frontend_bc/' || (echo "No frontend changes. Skipping build." && exit 0)

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend_bc
        gcloud app deploy --quiet --no-promote

timeout: 1600s
options:
  logging: CLOUD_LOGGING_ONLY
